//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public int Num { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
        public virtual Order Order { get; set; }
    }
}
