//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public OrderInfo()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string OrderName { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public string Address { get; set; }
        public string OrderDetail { get; set; }
        public int UserInfoId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
