//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime STime { get; set; }
        public string CName { get; set; }
        public string CPhone { get; set; }
        public string CAddress { get; set; }
        public string PostCode { get; set; }
        public string TransportWay { get; set; }
        public string PayWay { get; set; }
        public string Status { get; set; }
        public string UserUName { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
